### ISSUE TITLE
ASReview stat for datasets broken

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview-datatools#5]
```
jonathan$ asreview stat raw_data/demo.csv 
Traceback (most recent call last):
  File "/Users/jonathan/.pyenv/versions/asreview-production/bin/asreview", line 10, in <module>
    sys.exit(main())
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview-production/lib/python3.8/site-packages/asreview/__main__.py", line 80, in main
    entry.load()().execute(sys.argv[2:])
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview-production/lib/python3.8/site-packages/asreviewcontrib/statistics/entrypoint.py", line 66, in execute
    with StateStatistics.from_path(
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview-production/lib/python3.8/site-packages/asreviewcontrib/statistics/statistics.py", line 41, in from_path
    stat_inst = cls(path, *args, prefix=prefix, **kwargs)
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview-production/lib/python3.8/site-packages/asreviewcontrib/statistics/statistics.py", line 31, in __init__
    self.analysis = Analysis.from_path(path, prefix=prefix)
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview-production/lib/python3.8/site-packages/asreview/analysis/analysis.py", line 119, in from_path
    return cls.from_file(data_path, key=key)
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview-production/lib/python3.8/site-packages/asreview/analysis/analysis.py", line 107, in from_file
    state = state_from_file(data_fp)
  File "/Users/jonathan/.pyenv/versions/3.8.0/envs/asreview-production/lib/python3.8/site-packages/asreview/state/utils.py", line 139, in state_from_file
    raise ValueError(f"Expected ASReview file or file {data_fp} with "
ValueError: Expected ASReview file or file raw_data/demo.csv with extension ['.h5', '.hdf5', '.he5', '.json'].
```

@PeterLombaers might be the result of our changes in state file reader. Any idea?

**Comment by J535D165** [comment]
Turns out that this error shows up when dataset is poorly formatted. This should raise an informative exception.

**Comment by J535D165** [comment]
This issue is no longer relevant after the deprecation of asreview-statistics.
